//archivos de definicion

// Generated by https://quicktype.io

export interface Tweet {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: "tweet";
  _updatedAt: string;
  blockTweet: boolean;
  profileImg: string;
  text: string;
  username: string;
  image?: string;
}
